version: '3'
services:
  rest:
    build: ./Servidor/REST
    ports:
      - "5001:5001"
    volumes:
      - ./Servidor/shared:/shared
  soap:
    build: ./Servidor/SOAP
    ports:
      - "8002:8002"
    volumes:
      - ./Servidor/shared:/shared
  graphql:
    build: ./Servidor/GraphQL
    ports:
      - "5003:5003"
    volumes:
      - ./Servidor/shared:/shared
  grpc:
    build: ./Servidor/GRPC
    ports:
      - "5004:5004"
    volumes:
      - ./Servidor/shared:/shared
  shared:
    image: alpine
    volumes:
      - ./Servidor/shared:/shared
    command: tail -f /dev/null
