version: '3'
services:
  rest:
    build: ./servidor/rest
    ports:
      - "5001:5001"
  soap:
    build: ./servidor/soap
    ports:
      - "8002:8002"
  graphql:
    build: ./servidor/graphql
    ports:
      - "5003:5003"
  grpc:
    build: ./servidor/grpc
    ports:
      - "5004:5004"
  shared:
    image: alpine
    volumes:
      - ./shared:/shared
    command: tail -f /dev/null
